[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "teke"
description = 'A lightweight ASGI framework'
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
keywords = ["ASGI"]
authors = [
  { name = "Alex Kiura", email = "kiuraalex@gmail.com" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
  "pytest",
  "pytest-cov",
  "anyio",
  "uvicorn",
  "uvloop",
  "Werkzeug"
]
dynamic = ["version"]

[project.urls]
Documentation = "https://github.com/mrkiura/teke"
Issues = "https://github.com/mrkiura/teke/issues"
Source = "https://github.com/mrkiura/teke"

[tool.hatch.version]
path = "teke/__about__.py"

[tool.hatch.envs.default]
dependencies = [
  "pytest",
  "pytest-cov",
  "anyio",
  "uvicorn",
  "uvloop",
  "Werkzeug"
]
[tool.hatch.envs.default.scripts]
cov = "pytest --cov-report=term-missing --cov-config=pyproject.toml --cov=teke --cov=tests"
no-cov = "cov --no-cov"

[[tool.hatch.envs.test.matrix]]
python = ["310", "311"]

[tool.coverage.run]
branch = true
parallel = true
omit = [
  "teke/__about__.py",
]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]

[tool.hatch.build.targets.sdist]
exclude = [
  "/.github",
  "/docs",
]

[tool.hatch.build.targets.wheel]
packages = ["teke"]
